### PR TITLE
Fix spelling mistake: exclutions -> exclusions

### PR DESCRIPTION
**Pull request by shane-smith**
Simple spelling mistake fixed.

### CODE REVIEW

**Comment by joshk** [comment]
How come you closed this?

**Comment by joshk** [comment]
Thank you for the PR

**Comment by shane-smith** [comment]
Thanks @joshk - I wasn't sure if PRs were actively checked here. Seems they are :)

**Comment by joshk** [comment]
We can sometimes be a bit slow, sorry about that :)

**Pull request merged**
